### ISSUE TITLE
NO COLLABORATOR TAB ?!!?!?!??!!/

### ISSUE THREAD

**Issue by CrushingStar** [huskynp/Capstone#10]
HI, IM HERE TO MAKE A COMPLAINT ABOUT THE PROJECT. THERE IS NO CREDITS TAB FOR ME DESPITE THE ISSUES I PUT UP TO MAKE THIS PROJECT BETTER ?!!??!?!?! PLEASE PUT A PROJECT TAB WITH MY NAME 

THIS IS THE LEAST YOU COULD DO TO APPRECIATE MY HELP

**Comment by huskynp** [comment]
alright one sec

**Comment by huskynp** [comment]
added
