### ISSUE TITLE
CANNOT ACCESS CREDIT LINK WITHOUT LINK ???

### ISSUE THREAD

**Issue by CrushingStar** [huskynp/Capstone#11]
HELLO BEACH PUFFY, I SEE THAT YOU HAVE BECAME COMPETENT TO ADD A CREDIT SITE. HOWEVER, IT IS INACCESSIBLE TO THE PEOPLE THAT VISIT THE MAIN SITE. PLEASE ADD THE LINK SOMEWHERE ON THE MAIN SITE SO IT IS VISIBLE AND MY WORK IS APPRECIATED !!!!1

**Comment by Snoke10** [comment]
Hello CrushingStar I hope you are focusing

**Comment by huskynp** [comment]
https://huskynp.github.io/Capstone/credits there u go

**Comment by CrushingStar** [comment]
PLEASE ADD A HYPERLINK ON THE MAIN SITE THAT REDIRECTS TO THE CREDITS TAB SO I CAN HAVE MY 10 SECONDS OF EGO

**Comment by huskynp** [comment]
OKAY
