### ISSUE TITLE
LAST ISSUE OF THE PROJECT

### ISSUE THREAD

**Issue by CrushingStar** [huskynp/Capstone#15]
GREAT EFFORT I REALLY LIKE THE GRAPHICS THAT WENT INTO THIS. MR PATIL CONGRATULATIONS YOU GET A PROMOTION

**Comment by huskynp** [comment]
Omg! Thank you so much! I appreciate your EXCELLENT and PRODUCTIVE issues that helped me shape this project!!!!!!!!!!!!!!
