### ISSUE TITLE
FIRE IN 1917 TOO BIG

### ISSUE THREAD

**Issue by CrushingStar** [huskynp/Capstone#9]
HI, IM HERE TO MAKE A COMPLAINT ABOUT THE FINAL SCENE FOR 1917. THE FIRE IS TOO BIG, UNSYMMETRICAL, AND HURTS MY EYES!! PLEASE MAKE THE FIRE SMALLER AND MORE SYMMETRICAL SO MY EYES ARE OK

THANK YOU BEACH PUFFY

**Comment by huskynp** [comment]
fixed 🔢
